### PR TITLE
docs(golang driver): add some comments for use with GoDoc

### PR DESCRIPTION
**Pull request by mjholub**
some formatting changes were made automatically with gofumpt

### CODE REVIEW

**Review by jrgemignani — COMMENTED** [review]
I'm not sure if this is necessary. Thoughts? Justifications?

**Comment by mjholub** [comment]
hmm perhaps writing examples could be more beneficial, made that PR because the driver felt somewhat confusing to me at first. see other database libraries on godoc for comparison, like pgx or go-sqlite3

**Comment by mjholub** [comment]
Though if it may cause any merge conflict with anything that changes the codebase, please just merge the code changes first and then I'd happily rebase and remove any outdated comments

**Comment by jrgemignani** [comment]
@mjholub You should be able to rebase your PR's local branch with the AGE master and then do a force push to your remote mjholub:go-driver-documentation branch. That will cause the PR to be updated and should restart all of the PR checks.

**Comment by mjholub** [comment]
@jrgemignani yeah I know, it appears there are no conflicts though

**Review by jrgemignani — APPROVED** [review]

**Comment by jrgemignani** [comment]
@mjholub Please fill out the _optional extended description_ with a brief (few lines) description of your changes. You will likely need to do this locally and force push it to your remote branch to update this PR.

image

**Review by jrgemignani — CHANGES_REQUESTED** [review]
Request addition of extending commit description.

**Comment by jrgemignani** [comment]
@mjholub Can you please make the update so that I can merge the PR :)

**Comment by mjholub** [comment]
I'll take care of it soon

**Pull request closed without merging**
