### PR TITLE
Oid investigation

### PR DESCRIPTION
**Pull request by muhammadshoaib**
This branch tests uses of namespaces as OIDs instead of generating new one. 
We can solve this issue of OID using this way without adding much complex solution.

### CODE REVIEW

**Comment by jrgemignani** [comment]
I pulled it down and the build failed -

```
CREATE EXTENSION
============== running regression test queries        ==============
test graphid                      ... ok
test agtype                       ... ok
test cypher                       ... ok
test catalog                      ... FAILED
test scan                         ... ok
test expr                         ... FAILED
test cypher_create                ... ok
test cypher_match                 ... ok
test cypher_unwind                ... ok
test cypher_set                   ... ok
test cypher_remove                ... ok
test cypher_delete                ... ok
test cypher_with                  ... ok
test cypher_vle                   ... ok
test cypher_union                 ... ok
test cypher_merge                 ... ok
test age_load                     ... ok
test drop                         ... ok
============== shutting down postmaster               ==============

=======================
 2 of 18 tests failed.
=======================
```

Additionally, you need to make your commit comments more verbose -

```
commit 2fc8d73f284a8d7f827c05643c7953fa83d9281c
Author: Shoaib <muhemmed.shoaib@gmail.com>
Date:   Wed Mar 9 10:04:38 2022 +0100

    modified label ids

commit e99c2c785e83389fd6e8f4266df911117919ed17
Author: Muhammad Shoaib <muhemmed.shoaib@gmail.com>
Date:   Wed Mar 9 08:30:23 2022 +0100

    modified graph id from integer to serial

commit 4ef46d0aaec741e541d44ba122e0e80602b5d67a
Author: Muhammad Shoaib <muhemmed.shoaib@gmail.com>
Date:   Wed Mar 2 00:18:05 2022 +0100

    inital changes in graphid
```

**Comment by muhammadshoaib** [comment]
Both tests are failing because I didn't update the regression tests without consultations. Please have a look at diff file and advise if it is safe to update regression tests.

**Comment by jrgemignani** [comment]
I'm not so sure about using graphid, I do believe this was mentioned before with Alex's changes. graphid is too similar, if not identical, to other uses that it will cause confusion. If we are using the namespace as the id, we should name it so that is obvious. So, something like, graph_namespace_id.

**Comment by jrgemignani** [comment]
@muhammadshoaib Is this PR still needed?

**Comment by muhammadshoaib** [comment]
This pull request have already been incorporated in other pull requests for PG12 and PG13

**Pull request closed without merging**
