### PR TITLE
Age Swift Driver: Check if the graph exists and Readme updated

### PR DESCRIPTION
**Pull request by FahadZaheerfzr**
Added a method to check if the graph already exists otherwise create one. Added this method on start-up. Moreover added some descriptions in the Readme file

### CODE REVIEW

**Review by dehowef — CHANGES_REQUESTED** [review]
Hey Fahad, when you write a title for a commit, try to make it fit on one line, within the alotted 72 characters. That way your title is brief and readable without it cutting into the description. The description should detail what you did. I'm going to request you make a change to this commit

**Review by dehowef — COMMENTED** [review]
Is passing in the string that way safe? Line 75 in age.swift. Is the input being sanitized to prevent SQL Injections or other attacks?

**Comment by FahadZaheerfzr** [comment]
> Is passing in the string that way safe? Line 75 in age.swift. Is the input being sanitized to prevent SQL Injections or other attacks?

PostgreCllientKit provides basic protection against SQL injection attacks, and later we can add further security measures

**Comment by FahadZaheerfzr** [comment]
> Hey Fahad, when you write a title for a commit, try to make it fit on one line, within the alotted 72 characters. That way your title is brief and readable without it cutting into the description. The description should detail what you did. I'm going to request you make a change to this commit

Updated the title

**Comment by dehowef** [comment]
> > Hey Fahad, when you write a title for a commit, try to make it fit on one line, within the alotted 72 characters. That way your title is brief and readable without it cutting into the description. The description should detail what you did. I'm going to request you make a change to this commit
> 
> Updated the title

Please update the commit as well @FahadZaheerfzr 

> > Is passing in the string that way safe? Line 75 in age.swift. Is the input being sanitized to prevent SQL Injections or other attacks?
> 
> PostgreCllientKit provides basic protection against SQL injection attacks, and later we can add further security measures

That is good to hear, thank you for checking that

**Comment by FahadZaheerfzr** [comment]
The commit message is also updated

**Comment by dehowef** [comment]
@FahadZaheerfzr Great job !

**Review by dehowef — COMMENTED** [review]
Looks great. Official Approval comment since I replied in the thread.

**Pull request merged**
