### PR TITLE
[AGE Viewer desktop (Go)] Frontend development setup using Wails library in Golang.

### PR DESCRIPTION
**Pull request by AhmarZaidi**
Made the basic directory structure for frontend development of desktop app using [wails](https://github.com/wailsapp/wails) library in Golang.

Current state of the application:
image

---

This is meant to be the starting point for the desktop app development. The next step would be to add the UI elements and the functionality to the app.

- [x] Put the existing code in a separate directory `oldfiles` since they are not related to the Desktop Go Application at this point.
- [x] Basic frontend directory structure setup done
- [x] Set `github.com/apache/age` as the module name in `go.mod` file.
- [x] Used apache age logo as app logo.
- [x] Setup the landing page with age logo.

### CODE REVIEW

**Comment by aked21** [comment]
@AhmarZaidi, please fix the conflicts

**Comment by AhmarZaidi** [comment]
@aked21 I've fixed the conflicts.

**Comment by saadjameel** [comment]
@aked21 Go ahead please

**Comment by dehowef** [comment]
Outdated

**Pull request closed without merging**
