### PR TITLE
Driver Security Improvements: Python Driver Dependency Update (ANTLR)

### PR DESCRIPTION
**Pull request by aru-d-at**
Updated ANTLR:
4.9.2 -> 4.11.1

Used provide AGE grammar file for generation

**Testing Steps:**

- [x]  Run _setup.py_ -> SUCCESS
- [x]  Run _ test_age_py.py_ -> SUCCESS - [Output](https://github.com/apache/age/files/10810621/test_age_py.out.txt)
```
testChangeData (test_age_py.TestAgeBasic) ... ok
testCollect (test_age_py.TestAgeBasic) ... ok
testCypher (test_age_py.TestAgeBasic) ... ok
testExec (test_age_py.TestAgeBasic) ... ok
testMultipleEdges (test_age_py.TestAgeBasic) ... ok
testQuery (test_age_py.TestAgeBasic) ... ok

----------------------------------------------------------------------
Ran 6 tests in 3.720s

OK
```
- [x] Run _test_agtypes.py_ -> SUCCESS - [Output](https://github.com/apache/age/files/10810622/test_agtypes_py.out.txt)
```
test_path (test_agtypes.TestAgtype) ... ok
test_scalar (test_agtypes.TestAgtype) ... ok
test_vertex (test_agtypes.TestAgtype) ... ok

----------------------------------------------------------------------
Ran 3 tests in 0.038s

OK
```

### CODE REVIEW

**Review by dehowef — COMMENTED** [review]
The changes look good, though I have to ask-- are the *.interp and *.tokens files necessary to include in the commit? If I recall, they are files that are generated upon compilation. Please let me know if I am correct or not.

**Comment by aru-d-at** [comment]
Yes, looks like they are not needed. I have made necessary changes, as well as updated the readme & gitignore files.

**Review by dehowef — APPROVED** [review]
Looks good!! Nice work

**Review by dehowef — APPROVED** [review]
Looks good

**Pull request merged**
