### PR TITLE
Updated README.md; Grammar and format correction

### PR DESCRIPTION
**Pull request by kenwoon**
Corrected several grammar mistakes in some of the paragraphs, and also fixed inconsistent format in the 'Quick Start' code block using 'MATCH' clause.

### CODE REVIEW

**Review by dehowef — CHANGES_REQUESTED** [review]
Your change in line 333 created in a grammatical error please change it

**Comment by kenwoon** [comment]
> Your change in line 333 created in a grammatical error please change it

Fixed the grammatical error.

**Comment by dehowef** [comment]
@kenwoon Thanks-- can you squash the commits down to 1?

**Comment by jrgemignani** [comment]
@kenwoon @dehowef For just a README.md file we have this much in the commit description? Is this really necessary? It might be better to just redo this PR from scratch.

```
commit 22b7df2dc828cdf56f1f2f3ca23306d9ca0fc9ed
Author: Ken Woon <xk.woon@gmail.com>
Date:   Thu Apr 27 15:06:55 2023 -0700

    Updated README.md; Grammar correction

commit b729bafb58340860e50505fdc9e370954b0104b2
Merge: 77ec6390 2670af12
Author: Ken Woon <xk.woon@gmail.com>
Date:   Thu Apr 27 15:04:54 2023 -0700

    Merge branch 'patch-2' of https://github.com/kenwoon/age into patch-2

commit 77ec6390fa15a2ac4fb2e8a747575b9cd397e7ae
Author: Ken Woon <xk.woon@gmail.com>
Date:   Thu Apr 27 14:52:17 2023 -0700

    Updated README.md; Grammar correction

    Updated README.md; Grammar correction

commit 2670af129cdc0f867c9024029ef07e042c96745c
Author: Ken Woon <xk.woon@gmail.com>
Date:   Thu Apr 27 14:59:02 2023 -0700

    Updated README.md; Grammar correction

commit 7de42cb3885b5c778479f8b566dbb43d39aea4cb
Author: Ken Woon <xk.woon@gmail.com>
Date:   Thu Apr 27 14:52:17 2023 -0700

    Updated README.md; Grammar and format correction

commit f637ded7d3bf1d6e1267120cbdcfa1ee54ae77d9
Merge: d65412b2 d0323f96
Author: Ken Woon <xk.woon@gmail.com>
Date:   Thu Apr 27 13:09:39 2023 -0700

    Merge branch 'master' into patch-2

commit d65412b27f90e6282be848be887e03323eb93d6b
Author: Ken Woon <xk.woon@gmail.com>
Date:   Thu Apr 27 12:42:39 2023 -0700

    Revert "Merge branch 'patch-2' of https://github.com/kenwoon/age into patch-2"

    This reverts commit 2ee301047f8d24ec4cef92609a86587fe3f19413, reversing
    changes made to 387f536c9d82f172b7788d0d4782b5bb8ff5a526.

commit 2ee301047f8d24ec4cef92609a86587fe3f19413
Merge: 387f536c 1b329dd0
Author: Ken Woon <xk.woon@gmail.com>
Date:   Thu Apr 27 12:34:31 2023 -0700

    Merge branch 'patch-2' of https://github.com/kenwoon/age into patch-2

commit 387f536c9d82f172b7788d0d4782b5bb8ff5a526
Author: Ken Woon <xk.woon@gmail.com>
Date:   Sun Mar 12 21:31:18 2023 -0700

    Updated README.md; Grammar and format correction

    Corrected several grammar mistakes in some of the paragraphs, and also fixed inconsistent format in the 'Quick Start' code block using 'MATCH' clause.

    Fixed grammar errors

commit 1b329dd06ef9d66d8c5075c41274b25ea1dbe6dd
Merge: c1f1b364 9188a645
Author: Ken Woon <xk.woon@gmail.com>
Date:   Tue Apr 25 11:02:23 2023 -0700

    Merge branch 'master' into patch-2

commit c1f1b364dfbec6fe225af99fe5bd0f03539e47ca
Merge: cb94792d 3120bcb2
Author: Ken Woon <xk.woon@gmail.com>
Date:   Thu Apr 20 14:37:46 2023 -0700

    Merge branch 'master' into patch-2

commit cb94792d76adc3fc7170215b6f66a37582ba56e9
Author: Ken Woon <kenwoon@Kens-MacBook-Pro.local>
Date:   Thu Apr 20 14:35:36 2023 -0700

    Fixed grammar errors

commit 43e6fabe8890b252c0d461b66fdbf272a7cbe7c2
Author: Ken Woon <xk.woon@gmail.com>
Date:   Sun Mar 12 21:31:18 2023 -0700

    Updated README.md; Grammar and format correction

    Corrected several grammar mistakes in some of the paragraphs, and also fixed inconsistent format in the 'Quick Start' code block using 'MATCH' clause.
```

**Comment by kenwoon** [comment]
@dehowef My apologies, I have fixed the commit description.

**Comment by jrgemignani** [comment]
@kenwoon 
image

The first line, the single one by itself, should be a simple, short line, stating briefly what the commit is about.

The second block should be a more detailed description, but it also can be short. Both should also conform to being less than 80 characters per line.

You don't need any information like 

```
commit cb94792d76adc3fc7170215b6f66a37582ba56e9
Author: Ken Woon <kenwoon@Kens-MacBook-Pro.local>
Date:   Thu Apr 20 14:35:36 2023 -0700
```

**Comment by kenwoon** [comment]
@jrgemignani Thank you for the guideline. I have fixed the commit message.

**Comment by dehowef** [comment]
Merged, thank you

**Pull request merged**
