### PR TITLE
Added the toFloatList() function

### PR DESCRIPTION
**Pull request by M4rcxs**
- Basically the same function of OpenCypher toFloatList() https://neo4j.com/docs/cypher-manual/current/functions/list/#functions-tofloatlist
- toFloatList() converts a list of values and returns a list of floating point values. If any values are not convertible to floating point they will be null in the list returned.
- Returns a list containing the converted elements; depending on the input value a converted value is either a floating point value or null.
- Also added the regressions tests.

### CODE REVIEW

**Comment by dehowef** [comment]
This looks good to me so far upon my first look. Would you mind squashing the commits down into one while maintaining the description? Excellent work.

**Comment by M4rcxs** [comment]
> This looks good to me so far upon my first look. Would you mind squashing the commits down into one while maintaining the description? Excellent work.

Thank you!!

Can you verify if this rebase is right? I never did it before

**Comment by M4rcxs** [comment]
> This looks good to me so far upon my first look. Would you mind squashing the commits down into one while maintaining the description? Excellent work.

Thank you!!

**Comment by dehowef** [comment]
Hi, @M4rcxs can you edit the commit title to be descriptive of the changes as well.

**Comment by M4rcxs** [comment]
> Hi, @M4rcxs can you edit the commit title to be descriptive of the changes as well.

I've just done it!

**Comment by dehowef** [comment]
Hello @M4rcxs , the changes look good now and I will merge them shortly~ But, now that we have updated the master branch to PG13, to get these changes into the previous branches, PG11 and PG12, could you create 2 additional pull requests that want to merge into those branches? You can find them in the branch drop down. This goes for all PRs you make here on out (so the ones you made for toIntegerList() as well!) . :) Thanks for contributing and understanding.

**Comment by dehowef** [comment]
@M4rcxs can you make a PR of this for PG11?

**Comment by M4rcxs** [comment]
> @M4rcxs can you make a PR of this for PG11?

@dehowef I'm working on it, but I'm facing some issues with the PG version

**Comment by M4rcxs** [comment]
> @M4rcxs can you make a PR of this for PG11?

Done! did it at #1060

**Comment by dehowef** [comment]
@M4rcxs  Ty~

**Pull request merged**
