### PR TITLE
AGE Swift Driver: Readme updated

### PR DESCRIPTION
**Pull request by FahadZaheerfzr**
Add description of Apache Age Swift Driver

### CODE REVIEW

**Review by dehowef — CHANGES_REQUESTED** [review]
Hey Fahad, Your additions are great, but I don't think removing the licensing information from the readme file here is a good idea. You may want to check with @eyab on the License info requirements for each file.

**Comment by eyab** [comment]
@FahadZaheerfzr We can not remove the licenses. The license needs to remain on that page.

**Comment by FahadZaheerfzr** [comment]
Ah I saw the readme of other drivers and noticed there were no License. No worries I will update

**Comment by dehowef** [comment]
@FahadZaheerfzr That's a good thing to point out actually, we might need to add licensing info to those READMEs as well. @eyab thoughts?

**Comment by FahadZaheerfzr** [comment]
The requested changes are made and pushed @dehowef please check

**Review by dehowef — APPROVED** [review]

**Pull request merged**
