### PR TITLE
Added NULLIF() function

### PR DESCRIPTION
**Pull request by WendelLana**
PR for issue #908.

Added NULLIF() function that takes 2 arguments of "any" type (converting non-AGTYPE types to AGTYPE values) and return NULL if the two specified expressions are equal, if not returns the first expression.

Added regression tests.

### CODE REVIEW

**Comment by jrgemignani** [comment]
@WendelLana Is this PR necessary? There is a response in issue #908 stating how this could be done without this - 

image

Additionally, if it is necessary, you need to bring your PR up-to-date with the master branch -

image

**Comment by WendelLana** [comment]
@jrgemignani In my issue I've said using CASE would be an alternative to NULLIF too, but I find that the NULLIF() function is less verbose and simpler to use, even when nested. This is also part of a project ([Conditional Statement Improvements](https://github.com/orgs/AGEDB-INC/projects/15)) that you can find [here](https://github.com/orgs/AGEDB-INC/projects/15/views/1?pane=issue&itemId=18128198).

**Comment by jrgemignani** [comment]
@WendelLana Are AGDB-INC projects separate from AGE? Also, your build still fails.

**Comment by WendelLana** [comment]
@rafsun42 I don't believe so. However, there is an issue on the Neo4j repository about adding this function, and it's also easier to use and comprehend compared to a command like this:
`COALESCE(CASE columnname WHEN '' THEN NULL ELSE columnname END, 'STRING') `
or nested CASE clauses.

**Comment by rafsun42** [comment]
@WendelLana Could you elaborate about the issue you are referring to?

Could you also give a use case of `nullif` function?

**Comment by WendelLana** [comment]
I'm referring to this [issue](https://github.com/neo4j/neo4j/issues/1058) that shows one use case. I believe we could use it in some scenarios, for instance, when dividing by zero. Consider the following Cypher query:
````
MATCH (n)-[]->(m)
RETURN n.value / nullif (m.value, 0)
````

Additionally, I find this command:
````
RETURN NULLIF(n.value, m.value)
````
to be better and less verbose than:
````
RETURN 
    CASE n.value = m.value THEN NULL
    ELSE n.value
````
I know it may seem like a very specific case, but I genuinely think having a function like Postgres' `NULLIF` is beneficial as it promotes more integration between SQL and Cypher. This permits a simpler logic when writing a Cypher query using SQL-like logic.

**Pull request closed without merging**
