### PR TITLE
Fix issue 1033: access operator on vle edge lists

### PR DESCRIPTION
**Pull request by jrgemignani**
This patch fixes an issue where the edge lists generated by the vle function couldn't be resolved by the agtype_access_operator.

Added regression tests.

### CODE REVIEW

**Comment by dehowef** [comment]
Looks good to me.

**Review by muhammadshoaib — APPROVED** [review]
Approved.

**Review by MuhammadTahaNaveed — APPROVED** [review]
Looks good!

**Review by rafsun42 — APPROVED** [review]
Looks good

**Comment by jrgemignani** [comment]
Please hold off on merging this PR. After reviewing Taha's PR #1034, I feel that this one could incorporate some of his logic and could use some clarifying comments. Thank you @MuhammadTahaNaveed for your work too!

**Comment by jrgemignani** [comment]
@MuhammadTahaNaveed I will look at how this relates to #395.

**Comment by jrgemignani** [comment]
@MuhammadTahaNaveed #395 appears to have to do with a different issue, somewhere in the collect function.

**Comment by jrgemignani** [comment]
If everyone is happy with this PR - which has been modified - please merge it :)

**Comment by MuhammadTahaNaveed** [comment]
> @MuhammadTahaNaveed #395 appears to have to do with a different issue, somewhere in the collect function.

Oh okay..... 👍

**Comment by rafsun42** [comment]
> If everyone is happy with this PR - which has been modified - please merge it :)

@MuhammadTahaNaveed Could you merge this PR? :)

**Pull request merged**
