### PR TITLE
Modified the Volatility Category of functions age_asin and age_acos from STABLE TO IMMUTABLE

### PR DESCRIPTION
**Pull request by RC-002**
Reasons for the modification:

1) No database lookup 
2) No modification of the database 
3) Function is guaranteed to return the same constant results given the same arguments

### CODE REVIEW

**Comment by RC-002** [comment]
Thanks @Hunaid2000

**Comment by jrgemignani** [comment]
@RC-002 Please make your commit log entry more clear as to what was changed and why - 

```
* Stable to Immutable

* Update age--1.1.0.sql

Co-authored-by: RC-adaptive <rohan@adaptive.live>
```

It should state enough that someone knows what was done, to what, and why.

Other than that, good job!

**Comment by RC-002** [comment]
Thanks @jrgemignani.
I will definitely do that henceforth.

**Comment by jrgemignani** [comment]
@RC-002 Please make sure to correct this one as well :)

**Pull request merged**
