### PR TITLE
Fix property constraints against resolved variables (#701)

### PR DESCRIPTION
**Pull request by jrgemignani**
Fixed an issue where an already resolved variable, when used for
a property constraint, errored out. See #701 for more details.

This also fixed a regression test that was erroring out, but was
overlooked.

Adjusted and added additional regression tests.

Co-authored-by: Dehowe Feng <dehowefeng@gmail.com>

### CODE REVIEW

**Comment by dehowef** [comment]
John and I worked closely on this issue to resolve the limitations of the match clause in reflexive pattern matching. If anyone wants to take a look and review what was done, it would be much appreciated

**Comment by MuhammadTahaNaveed** [comment]
Hi @dehowef @jrgemignani,

I was wondering why the query mentioned in issue still errors out. 
```
SELECT * from cypher('my_graph_name', $$
  MATCH (a {prop: “val”})-[]- (a {prop2: “val2”})
$$) as (a agtype);
```
I tried this query in regression tests
```
SELECT * FROM cypher('cypher_match', $$
	MATCH (a {i: 1})-[]-(a {j: 2}) RETURN a $$) as (a agtype);
ERROR:  variable a already exists
LINE 2:  MATCH (a {i: 1})-[]-(a {j: 2}) RETURN a $$) as (a agtype);
```

**Comment by jrgemignani** [comment]
@MuhammadTahaNaveed Actually, that's a good point and a bit of an oversight on my part. My PR fixes the clause to clause previously resolved variables, not within the same clause. I will try to add that in tomorrow and update this PR.

**Comment by dehowef** [comment]
@MuhammadTahaNaveed The issues with MATCH occur in several sections of the code-- we have chosen to address them incrementally for maximum transparency and visibility for the project.

I feel like this method as several advantages, being that each commit will be itemized so that in the event that something is updated, we can go back to the commit where a certain change was implemented to easily view and address it. Thanks!

**Comment by jrgemignani** [comment]
@dehowef @MuhammadTahaNaveed I'm reviewing my patch to make sure it covers all the cases adequately.

**Comment by jrgemignani** [comment]
@dehowef @MuhammadTahaNaveed I have updated the PR to point to the correct issue this PR resolves. If you can verify that it works against that issue? Sorry, for the confusion.

**Pull request merged**
