### PR TITLE
Fix json serialization error in Python Driver

### PR DESCRIPTION
**Pull request by omaurel-socha**
* Added test to catch the error in toJson()
* removed the trailing comma in _nodeToJson() node.properties part
* removed the trailing comma in _nodeToString() node.properties part

### CODE REVIEW

**Review by markgomer — APPROVED** [review]

**Comment by jimenasansav** [comment]
Hi @dehowef 
Could you please help us proceed with this PR?
Thank you!

**Comment by jrgemignani** [comment]
@omaurel-socha @markgomer @jimenasansav Can the creator of this PR update it to correct conflicts?

image

**Comment by jrgemignani** [comment]
@omaurel-socha I have added @dehowef and @rafsun42 as reviewers.

**Comment by dehowef** [comment]
Looks good to me.

**Pull request merged**
