### PR TITLE
Issue #388 - Fix python driver build from source

### PR DESCRIPTION
**Pull request by Hunaid2000**
See details in issue #388.

- Changed required version of antlr4-python3-runtime to 4.9.3
- Moved required packages to requirements.txt so that user can easily install all packages with one command
- Updated the readme accordingly (I feel Readme is unclear)
- Fixed a typo in exceptions.py file

### CODE REVIEW

**Review by jrgemignani — APPROVED** [review]

**Comment by jrgemignani** [comment]
@Hunaid2000 Looks good to me. 
@dehowef I will let you give it a final review and merge if acceptable.

**Comment by dehowef** [comment]
@Hunaid2000 Your changes look good-- Before I approve these changes, were you able to get the python driver to compile with these changes?

**Comment by Hunaid2000** [comment]
Yes works fine on my side with antlr4-python3-runtime v4.9.3 and other changes.

**Comment by dehowef** [comment]
@Hunaid2000 That's great! We can go ahead and close it and merge the changes then. Thank you for your time and effort!!!

**Review by dehowef — APPROVED** [review]

**Pull request merged**
