### PR TITLE
add regression tests for delete_global_graphs

### PR DESCRIPTION
**Pull request by rafsun42**

### CODE REVIEW

**Review by dehowef — COMMENTED** [review]
Rafsun, these tests look good to me-- Just one thing about the Makefile, make sure the indentation is done correctly, otherwise well done.

**Comment by jrgemignani** [comment]
@rafsun42 I agree with @dehowef, very well done. Just check the Makefile indentation, as it doesn't look correct, as @dehowef mentioned.

**Comment by rafsun42** [comment]
@dehowef @jrgemignani Fixed the indentation issue.

**Comment by jrgemignani** [comment]
Good job @rafsun42 !

**Pull request merged**
