### PR TITLE
Refactor Dockerfile to use multi-stage builds

### PR DESCRIPTION
**Pull request by shinyaaa**
Refactored Dockerfile to use multi-stage builds for reduction image size.

The installation of the packages required for the build and the build process are carried out at the build stage. The built binaries are then placed in the final image.

This changes has reduces the image size about 1/3.
```
$ docker image ls apache/age
REPOSITORY   TAG       IMAGE ID       CREATED          SIZE
apache/age   tmp       5ffd0b539a88   22 minutes ago   458MB <-- New image
apache/age   latest    fb44b5789198   2 months ago     1.5GB <-- Original image
```

### CODE REVIEW

**Comment by jrgemignani** [comment]
@shinyaaa You will need to rebase and force update your PR. Please see PR #2007 for more information.

**Comment by shinyaaa** [comment]
@jrgemignani 

> @shinyaaa You will need to rebase and force update your PR. Please see PR #2007 for more information.

Thanks, rebased.

**Comment by MuhammadTahaNaveed** [comment]
@shinyaaa Nice work. Could you please add these changes to Dockerfile.dev as well. Thanks.

**Comment by shinyaaa** [comment]
@MuhammadTahaNaveed 
I don't know what Dockerfile.dev is used for, but I didn't change it because I thought that if it is for development use, it should contain development packages.

Should I modify Dockerfile.dev as well?

**Comment by shinyaaa** [comment]
I found a similar [issue](https://github.com/apache/age/issues/362) and refer to it.

**Comment by MuhammadTahaNaveed** [comment]
> @MuhammadTahaNaveed I don't know what Dockerfile.dev is used for, but I didn't change it because I thought that if it is for development use, it should contain development packages.
> 
> Should I modify Dockerfile.dev as well?

Yeah you are right, lets leave it as it is.

**Review by MuhammadTahaNaveed — APPROVED** [review]
looks good to me

**Comment by MuhammadTahaNaveed** [comment]
@shinyaaa Please create PRs for branches PG11, PG12, PG13, PG14, PG15 and PG16 as well. Thank you.

**Comment by shinyaaa** [comment]
@MuhammadTahaNaveed 
Created PR for each branch. I also verified that the images created in each Dockerfile worked properly.

**Pull request merged**
