### PR TITLE
Fix bogus failure of test expr

### PR DESCRIPTION
**Pull request by saygoodbyye**
All discussions were conducted in #1439 
Changes:

1) force_parallel_mode was set to 'regress' to avoid "CONTEXT: parallel worker" message appear
2) fixed unsorted output in the specified query

### CODE REVIEW

**Comment by aked21** [comment]
@rafsun42, please review this PR.

**Comment by rafsun42** [comment]
@aked21 Merged.
@saygoodbyye Could you please create this PR for PG14, 13, 12 and 11 branch as well?

**Review by rafsun42 — COMMENTED** [review]
approved

**Comment by jrgemignani** [comment]
Please fix this PR, it increased the runtime of the regression test for expr by ~5 times.

**Comment by jrgemignani** [comment]
@rafsun42 @saygoodbyye This PR is at risk of being rolled back completely if the issue of the 5x increase in regression runtime is not resolved. Please make the changes that are necessary more targeted.

**Comment by rafsun42** [comment]
@jrgemignani @saygoodbyye Created a PR #1772 addressing the issue. We can move this discussion there.

**Pull request merged**
