### PR TITLE
Fix python driver's test

### PR DESCRIPTION
**Pull request by KTaskn**
Fixed a problem with python driver testing where arguments were not working properly.

### CODE REVIEW

**Comment by dehowef** [comment]
It works fine for me. Can you show me how it didn't work for you

**Comment by dehowef** [comment]
Maybe you can remove "dehowefeng" in the DSN string though and replace that with something generic

**Comment by KTaskn** [comment]
@dehowef 

It is not consistent with the readme, it should be able to be changed dynamically from the arguments as in the readme.
Also, it is strange that your handle is in the code.

https://github.com/apache/age/blob/5fbe064a913f03dd13058cc21b7b7fb0cdf910cb/drivers/python/README.md?plain=1#L48C1-L57C4

**Comment by aked21** [comment]
@dehowef, can you comment if this can be merged?

**Comment by dehowef** [comment]
Closed for breaking the regression tests.

**Pull request closed without merging**
