### PR TITLE
Introduce age_pi and age_rand functions and related updates

### PR DESCRIPTION
**Pull request by mohayu22**
Resolved issue #791 

- Added `age_pi` and `age_rand`
- Added new regression tests

**Problem:**
In order to maintain compatibility with the agtype data type, all values used as properties of vertices and edges must be of the agtype type. When setting a property, such as `SET n.i = 3.1415`, the float value is first converted into agtype using the `float_to_agtype` function before being passed to postgres. Similarly, other conversion functions like `integer_to_agtype` and `string_to_agtype` are used as needed.

When a function like `pi` is used with a typecast, such as `SET n.i = pi()::int`, the function is executed, typecasted, and converted to agtype before being passed to postgres.

However, when using functions like `rand` or `pi` without a typecast, such as `SET n.i = pi()`, the function is passed directly to postgres and returns a float value that is not automatically converted into agtype. This can result in a segmentation fault.

**Solution:**
One potential solution is creating wrapper functions for the `drandom` and `dpi` ("d" stands for "double precision") functions of postgres, which would convert their output into agtype before passing it to postgres. 

**Changes:**
This pull request aims to resolve this problem by introducing the `age_rand` and `age_pi` functions. The creation of these functions involves adding related SQL code in the _age--1.2.0.sql_ file, and their C implementation in the _agtype.c_ file. 

The `age_pi` function is marked as `IMMUTABLE` but `age_rand` is not.

The C implementation uses the postgre `drandom` and `dpi` functions, which are located in the _float.c_ file. The `DirectFunctionCall1` macro is used to call these functions. The float return value of these functions is then converted to agtype.

**Grammer File:**
In _cypher_gram.c_, function node (fnode) is created for both age functions and those that directly mapped to postgres functions. However, after adding `age_rand` and `age_pi` functions, the code related to mapped functions `random` and `pi` is removed.

**Regression Tests:**
Regression tests have been added for these new functions. For testing `rand`, `n.i < 1 AND n.i >= 0` logic is used which would return `true` to pass.

### CODE REVIEW

**Comment by jrgemignani** [comment]
@mohayu22 Please update your commit description, the big box, to give a description of what was done and why. Make sure to conform to the archaic :) 80 columns per line of text.

image

**Comment by mohayu22** [comment]
@jrgemignani Done

**Comment by jrgemignani** [comment]
@mohayu22 It still shows the same for the commit description,...

**Comment by mohayu22** [comment]
I have updated the PR description.

**Comment by jrgemignani** [comment]
image

**Comment by mohayu22** [comment]
@jrgemignani I have changed the commit messages.

**Pull request merged**
