### PR TITLE
Load Age from the plugins directory to facilitate non-superuser usage

### PR DESCRIPTION
**Pull request by daanwa**
Add a parameter to main `connect` function that signals the library to load the Apache Age extension from the PostgreSQL plugins folder.

This is in relation to issue [839](https://github.com/apache/age/issues/839)

@rafsun42 the previous Pull Request [1926](https://github.com/apache/age/pull/1926) was closed due to unintended commits. This is the new one.

### CODE REVIEW

**Review by rafsun42 — APPROVED** [review]

**Comment by rafsun42** [comment]
@daanwa Looks good to me. I made some modification to the commit message before merging.

**Comment by rafsun42** [comment]
@daanwa Could you please cherry pick this commit and send PR for other PG branches, such as PG13, PG14, PG15, PG16.

**Comment by daanwa** [comment]
@rafsun42 not sure how I would go about this. Do I just sync all the required branches to my own fork, cherry-pick there and than request merge request for each individual branch? Or is there a better way to do this?

**Comment by rafsun42** [comment]
@daanwa Yes, that's how we do it. I know it can be a bit tedious.

**Comment by daanwa** [comment]
@rafsun42 No problem, its done. When do you think this can be pushed to pypi?

**Pull request merged**
