### PR TITLE
[GDBMS_cypher] e(), date() and localtime() functions

### PR DESCRIPTION
**Pull request by GhostVaibhav**
This PR adds the following functions: 
- [x] e()
- [x] localtime_c()
- [x] date()

### CODE REVIEW

**Comment by GhostVaibhav** [comment]
The function `localtime()` is renamed as `localtime_c()` due to naming conflicts with the default functions present in Postgres.

**Comment by emotionbug** [comment]
It's a good idea to write tests together so that you can communicate to the other person that the code is working the way you want it to and that this is what you intended.

**Comment by GhostVaibhav** [comment]
Alright, that means to bundle certain testcases at the top of the respective functions as comments?

**Comment by emotionbug** [comment]
Nope. refer here.
https://github.com/apache/age/tree/GDBMS_cypher/src/test/regress

**Comment by GhostVaibhav** [comment]
Added tests for the e() function [[b383661](https://github.com/apache/age/pull/698/commits/b3836613b4adea53531965d4e97b24a4fc3242d2)]. Need assistance for writing tests for localtime_c() and date() functions.

**Pull request closed without merging**
