### PR TITLE
Driver Security Improvements:  Go Driver Dependencies

### PR DESCRIPTION
**Pull request by aru-d-at**
- ANTLR v4.9.2 -> v4.11.1

- Go Dependencies

- Parser README

**### TESTING  Steps:**

 - [x] Run `go get -u ./...` -> SUCCESS
 - [x] Run `go test ./...` -> SUCCESS - [Output](https://github.com/apache/age/files/10820647/test_age_go.out.txt)

### CODE REVIEW

**Comment by jrgemignani** [comment]
@aru-d-at @dehowef Do we need to have the generated files on github?

**Comment by aru-d-at** [comment]
@jrgemignani 

Did you mean the interface related files inside the parser folder? I had already removed the unneeded generated *.token and *.interp files prior to commit.

**Comment by dehowef** [comment]
@jrgemignani @aru-d-at On the ANTLR modification for the python driver, I asked Arun to remove the generated files from the commit-- I think he would apply similar logic to this one as well. As far as I can see, there are no generated files. Looks good to me.

**Comment by jrgemignani** [comment]
> @jrgemignani @aru-d-at On the ANTLR modification for the python driver, I asked Arun to remove the generated files from the commit-- I think he would apply similar logic to this one as well. As far as I can see, there are no generated files. Looks good to me.

I'm referring to the age_*.go files in golang/parser. All of them are generated by Age.g4 it looks like. We can probably remove them all.

**Comment by dehowef** [comment]
> > @jrgemignani @aru-d-at On the ANTLR modification for the python driver, I asked Arun to remove the generated files from the commit-- I think he would apply similar logic to this one as well. As far as I can see, there are no generated files. Looks good to me.
> 
> I'm referring to the age_*.go files in golang/parser. All of them are generated by Age.g4 it looks like. We can probably remove them all.

@aru-d-at can you go and see if it is possible to remove these files from the repository? Thank you

**Comment by aru-d-at** [comment]
> > > @jrgemignani @aru-d-at On the ANTLR modification for the python driver, I asked Arun to remove the generated files from the commit-- I think he would apply similar logic to this one as well. As far as I can see, there are no generated files. Looks good to me.
> > 
> > 
> > I'm referring to the age_*.go files in golang/parser. All of them are generated by Age.g4 it looks like. We can probably remove them all.
> 
> @aru-d-at can you go and see if it is possible to remove these files from the repository? Thank you

@dehowef @jrgemignani Various functions and interfaces from the parser folder are used in the 'builder.go' and 'mapper.go'. These are just some of the ones in first few lines.

image
image
image
image

**Comment by jrgemignani** [comment]
@aru-d-at I just checked and they [**.go** files in **parser**] are generated by **antlr4**. However, we don't provide **antlr4** in our package, just the runtime. It looks like if those file aren't there, it would be a pain for anyone to regenerate them manually. So, ignore my concerns about the **.go** files in **parser**.

**Comment by aru-d-at** [comment]
@jrgemignani @dehowef So in that case all good for the merge?

**Comment by jrgemignani** [comment]
Hmmmm,... did you regenerate these files or just edit them?

image

**Comment by aru-d-at** [comment]
@jrgemignani All parser files are generated. I needed to edit the _antlr_ import statement to reflect newer import path for v4.11.1 for **mapper** and **builder** inside **age** folder.

**Comment by jrgemignani** [comment]
> @jrgemignani All parser files were generated then licenses were edited in. I needed to edit the _antlr_ import statement to reflect newer import path for v4.11.1 for **mapper** and **builder** inside **age** folder.

Is it possible to add something to the go driver to automatically build these files or something in a README explaining how to build them so that we don't need to include the generated files in the distribution?

**Comment by aru-d-at** [comment]
@jrgemignani I have this Batch script ready for Windows and have tested it.

I also have the Bash script ready and tested on Linux but, haven't found a way to test it on Mac yet.

Should I go ahead and commit them?

**Batch script**
```
@echo off
setlocal

set "minimum_version=1.18"
set "installed_version="
set "download_url=https://go.dev/dl/go1.19.7.windows-amd64.msi"

:: Check if Go is installed and get its version
set "go_path="
for %%i in (go.exe) do set "go_path=%%~$PATH:i"
if defined go_path (
	for /f "tokens=3" %%v in ('go version 2^>^&1') do set "installed_version=%%v"
)

:: If Go is not installed or the version is less than 1.18, prompt the user to install a new version
if not defined installed_version (
	echo installing Go
	:: Download and install the latest version of Go
	powershell -Command "& {Invoke-WebRequest -Uri "%download_url%" -OutFile '%TEMP%\go-minimum-version.msi'}"
	start /wait msiexec /i "%TEMP%\go-minimum-version.msi"
	for /f "tokens=3" %%v in ('go version 2^>^&1') do set "installed_version=%%v"
) else if "%installed_version%" lss "%minimum_version%" (
    set /p "install_new_version=Go version %minimum_version% or higher is required. Would you like to install the latest version? (y/n)"
    if /i "%install_new_version%"=="y" (
        :: Download and install the latest version of Go
        powershell -Command "& {Invoke-WebRequest -Uri "%download_url%" -OutFile '%TEMP%\go-minimum-version.msi'}"
        start /wait msiexec /i "%TEMP%\go-minimum_version.msi"
        for /f "tokens=3" %%v in ('go version 2^>^&1') do set "installed_version=%%v"
    ) else (
        echo Please update Go version before installing driver.
        goto end
    )
)

:: Echo "a", "b", and "c"
echo a
echo b
echo c
pause
:end
pause
endlocal
```

**Comment by jrgemignani** [comment]
@aru-d-at I believe that a decision on this is up to @dehowef 

That being said, I do think that if we can have these files autogenerated on the users machine, then we won't need to track them in the repo. Being that they are autogenerated, we shouldn't track them in the repo.

**Comment by dehowef** [comment]
@aru-d-at go ahead and commit it

**Comment by dehowef** [comment]
@aru-d-at but yeah we should remove as many auto generated files as possible-- there is no need to track those unless absolutely necessary

**Comment by aru-d-at** [comment]
@dehowef I have pushed the scripts after testing on all 3 OS's

**Comment by aru-d-at** [comment]
@dehowef Seems the Go Workflow needed to be updated as well as a Go Target Generation file.

**Comment by aru-d-at** [comment]
@dehowef Updated the workflow again since generation was failing as ANTLR jar is non-existent. Hopefully workflow works now. (If it doesn't may need to inspect Java dependency in yml)

**Comment by dehowef** [comment]
@aru-d-at Yeah, it still seems to be failing 2 tests-- this issue has been plaguing us for awhile

**Comment by aru-d-at** [comment]
@dehowef Sorry, my bad, I should have run workflow on a separate repo first.
Should work now.
image

**Comment by dehowef** [comment]
@aru-d-at All checks passed. Great work! I'll merge it now

**Pull request merged**
