### PR TITLE
Apache Age Swift Driver: Methods added to check for the graph and Readme updated

### PR DESCRIPTION
**Pull request by FahadZaheerfzr**
Added a method to check if the graph already exists otherwise create one. Added this method on start-up. Moreover added some description in the Readme file

### CODE REVIEW

**Comment by dehowef** [comment]
Hi Fahad, can you explain the changes made in setUpAge to me? In the file drivers/age-swift/Sources/age-swift/age.swift, at line 23.

**Comment by FahadZaheerfzr** [comment]
> Hi Fahad, can you explain the changes made in setUpAge to me? In the file drivers/age-swift/Sources/age-swift/age.swift, at line 23.

Alright, so on line 23 Previously only the connection was passed as the argument, now the graph name is also being passed to check if the graph already exist or it creates one.

**Comment by dehowef** [comment]
Great. It looks like there was some white space added on lines 37 and 38 in the file drivers/age-swift/Sources/age-swift/age.swift. If you could go ahead and remove that, I think everything else looks good @FahadZaheerfzr

**Comment by FahadZaheerfzr** [comment]
Done but now I can not squash my commits to one commit. Can you please squash them into one commit?

> Great. It looks like there was some white space added on lines 37 and 38 in the file drivers/age-swift/Sources/age-swift/age.swift. If you could go ahead and remove that, I think everything else looks good @FahadZaheerfzr

**Comment by dehowef** [comment]
I think you can squash it yourself. Please research how.

**Pull request closed without merging**
