### PR TITLE
adding missing parser files

### PR DESCRIPTION
**Pull request by ezeeyahoo**
generated using age/drivers/golang/parser/generate.sh

### CODE REVIEW

**Comment by ezeeyahoo** [comment]
Please, if someone from maintainers group do a review of this PR..

**Comment by MuhammadTahaNaveed** [comment]
> Please, if someone from maintainers group do a review of this PR..

Hi @ezeeyahoo, thanks for the pr.

There was previously a discussion on this thing here https://github.com/apache/age/pull/714, can you please go through it?

**Comment by jrgemignani** [comment]
@ezeeyahoo Why is this needed, these files are meant to be autogenerated.

**Comment by maehara-n** [comment]
The automatuc generation of files does not seem to be working.

operating environment
* golang 1.21.5
* Get driver with gomod
　github.com/apache/age/drivers/golang v0.0.0-20231212232227-0ea118689d78

The following error is output when building the application.


```
#0 5.670 # github.com/apache/age/drivers/golang/age
#0 5.670 /go/pkg/mod/github.com/apache/age/drivers/golang@v0.0.0-20231212232227-0ea118689d78/age/builder.go:42:22: undefined: parser.AgeParser
#0 5.670 /go/pkg/mod/github.com/apache/age/drivers/golang@v0.0.0-20231212232227-0ea118689d78/age/builder.go:43:21: undefined: parser.AgeVisitor
#0 5.670 /go/pkg/mod/github.com/apache/age/drivers/golang@v0.0.0-20231212232227-0ea118689d78/age/builder.go:114:9: undefined: parser.AgeVisitor
#0 5.670 /go/pkg/mod/github.com/apache/age/drivers/golang@v0.0.0-20231212232227-0ea118689d78/age/builder.go:129:52: undefined: parser.AgeoutContext
#0 5.670 /go/pkg/mod/github.com/apache/age/drivers/golang@v0.0.0-20231212232227-0ea118689d78/age/builder.go:135:52: undefined: parser.VertexContext
#0 5.670 /go/pkg/mod/github.com/apache/age/drivers/golang@v0.0.0-20231212232227-0ea118689d78/age/builder.go:151:50: undefined: parser.EdgeContext
#0 5.670 /go/pkg/mod/github.com/apache/age/drivers/golang@v0.0.0-20231212232227-0ea118689d78/age/builder.go:164:50: undefined: parser.PathContext
#0 5.670 /go/pkg/mod/github.com/apache/age/drivers/golang@v0.0.0-20231212232227-0ea118689d78/age/builder.go:186:51: undefined: parser.ValueContext
#0 5.670 /go/pkg/mod/github.com/apache/age/drivers/golang@v0.0.0-20231212232227-0ea118689d78/age/builder.go:201:56: undefined: parser.PropertiesContext
#0 5.670 /go/pkg/mod/github.com/apache/age/drivers/golang@v0.0.0-20231212232227-0ea118689d78/age/builder.go:216:50: undefined: parser.PairContext
#0 5.670 /go/pkg/mod/github.com/apache/age/drivers/golang@v0.0.0-20231212232227-0ea118689d78/age/builder.go:216:50: too many errors
```

**Comment by jrgemignani** [comment]
@ezeeyahoo PR #1582 should have addressed this. Is this PR still needed?

**Comment by ezeeyahoo** [comment]
No problem, closing it.
Thanks for incorporating required changes.

**Pull request closed without merging**
