### PR TITLE
Merge actions

### PR DESCRIPTION
**Pull request by vinzenz**
An attempt to add support for merge actions to AGE. This is currently WIP and I will need some help understanding the code a bit better.
Currently I am lost on what to do with the parsed code, to be able handling the on create/on match cases.

I somehow don't understand how everything works at this moment, so I will need some pointers or some explanation how to continue, if one of you is willing to do so, it would be much appreciated, for me it's a big missing piece to the puzzle on making it convenient to use, otherwise I will be forced to have a lot of round trips to the server for data insertion/updates.

Signed-off-by: Vinzenz Feenstra <evilissimo@gmail.com>

### CODE REVIEW

**Comment by JoshInnis** [comment]
Hi @vinzenz,

**Comment by JoshInnis** [comment]
Hi @vinzenz 

So a couple things. Merge actions is an issue that we need to address, so thank you for trying to get the ball rolling. :). BUT, you need to do more than change the expected out from the regression tests if you change the regression SQL, AND you need to throw an error if a user inputs a grammatically correct statement with MERGE actions that we cannot currently handle.

**Comment by jrgemignani** [comment]
@vinzenz @JoshInnis What is the current status of this PR? The PR looks to need, at the very least, to be rebased against the current master branch. But, it is not known if there was a plan to go forward, or not at all.

**Comment by vinzenz** [comment]
@jrgemignani well it looks like, i don't have the knowhow to finish it and not enough time to get it in, so i will close it.
It was marked as draft already anyway as it is not even nearly finished.


Closing

**Comment by jrgemignani** [comment]
@vinzenz Thank you for the quick response and the attempt! I will try to see about getting MERGE actions added to our list of tasks.

**Pull request closed without merging**
