### PR TITLE
Fix issue 1043: ERROR:  container must be an array or object

### PR DESCRIPTION
**Pull request by jrgemignani**
Fixed issue 1043 -

ERROR:  container must be an array or object

This was cause by agtype_access_operator not recognizing and decoding a VLE path container.

Added regression tests.

### CODE REVIEW

**Comment by jrgemignani** [comment]
If anyone has a few more regression tests for this, that would be great.

**Comment by jrgemignani** [comment]
When merging, please make sure not to clear this out -
image

**Review by MuhammadTahaNaveed — APPROVED** [review]
Looks good 👍

**Review by rafsun42 — APPROVED** [review]
Look good.

**Pull request merged**
