### PR TITLE
Minor fix in `agtype_volatile_wrapper` function

### PR DESCRIPTION
**Pull request by WendelLana**
Fixed duplicated IF-STATEMENT of INT4OID in `agtype_volatile_wrapper` function changing it to INT2OID as the case dealt with a 2-byte signed integer (16-bit) data type.

### CODE REVIEW

**Comment by WendelLana** [comment]
@rafsun42 done!

**Comment by rafsun42** [comment]
@WendelLana Could you create this pr for other PG** branches?

**Comment by WendelLana** [comment]
@rafsun42 Sure, I'll do it

**Comment by rafsun42** [comment]
@WendelLana FYI, PRs needs to be sent to all five of PG11, PG12, PG13, PG14, PG15.

**Pull request merged**
