### PR TITLE
Removing Duplicate Lines Of Code

### PR DESCRIPTION
**Pull request by fatimafatimaprogrammer**
There was duplicate lines of code in "cypher_create.sql" file  on line number 191 and 209 which i came across while exploring different files in SQL Folder.Which looks odd, so i removed those duplicate lines.
please consider to apply my little fix.

### CODE REVIEW

**Comment by MuhammadTahaNaveed** [comment]
Hello,

You should also update the `regress/expected/create_cypher.out` file in order to pass the failing regression tests.

image

**Comment by fatimafatimaprogrammer** [comment]
> Hello,
> 
> You should also update the `regress/expected/create_cypher.out` file in order to pass the failing regression tests.
> 
> image

Thank you for mentioning the issue Let me update

**Comment by imranzaheer612** [comment]
Observe the `regression.diffs`. Try Remove the lines with `(-, !)` symbols, then run test again. Now again observe the `regression.diffs` output. It will show which lines are needed to be added (lines with symbol `+`). Add those lines. I guess it will work. 

`install check` command will perform the regression test.

**Comment by jrgemignani** [comment]
@fatimafatimaprogrammer @imranzaheer612 I am not sure that these are **unnecessary** duplicates. It is likely that they are purposeful done for testing the prepared statements and functions, as those are cached and run multiple times.

@JoshInnis ?
```
7ba89b01 regress/sql/cypher_create.sql (Josh Innis     2021-03-31 18:10:16 -0700 190) EXECUTE p_1;
7ba89b01 regress/sql/cypher_create.sql (Josh Innis     2021-03-31 18:10:16 -0700 191) EXECUTE p_1;

7ba89b01 regress/sql/cypher_create.sql (Josh Innis     2021-03-31 18:10:16 -0700 208) SELECT create_test();
7ba89b01 regress/sql/cypher_create.sql (Josh Innis     2021-03-31 18:10:16 -0700 209) SELECT create_test();
```

**Comment by fatimafatimaprogrammer** [comment]
> @fatimafatimaprogrammer @imranzaheer612 I am not sure that these are **unnecessary** duplicates. It is likely that they are purposeful done for testing the prepared statements and functions, as those are cached and run multiple times.
> 
> @JoshInnis ?
> 
> ```
> 7ba89b01 regress/sql/cypher_create.sql (Josh Innis     2021-03-31 18:10:16 -0700 190) EXECUTE p_1;
> 7ba89b01 regress/sql/cypher_create.sql (Josh Innis     2021-03-31 18:10:16 -0700 191) EXECUTE p_1;
> 
> 7ba89b01 regress/sql/cypher_create.sql (Josh Innis     2021-03-31 18:10:16 -0700 208) SELECT create_test();
> 7ba89b01 regress/sql/cypher_create.sql (Josh Innis     2021-03-31 18:10:16 -0700 209) SELECT create_test();
> ```

Yes after exploring and understanding further i think so too because initially i tried to fix failing test for cypher-create but by fixing that it gives failing test for graph generation file.
so I think that lines of code which seems duplicate to me initially are not actually duplicate as in cypher-create.out file it have different ids.
Thats what my understanding about this correct me if i'm wrong.
Thank you!!

**Comment by jrgemignani** [comment]
Then it doesn't sound like this PR is needed.

**Pull request closed without merging**
