### PR TITLE
Edited a typo in the readme file of driver support for python and made some changes i.e. added references and adjusted a heading.

### PR DESCRIPTION
**Pull request by TalhaMunir-JD**
Edited a typo in the readme file of driver support for python and made some changes i.e. added references and adjusted a heading.

### CODE REVIEW

**Comment by jrgemignani** [comment]
@TalhaMunir-JD Please rebase this PR with the current *master* branch.

**Comment by jrgemignani** [comment]
@TalhaMunir-JD Please explain why these changes are necessary? What value are you adding?

**Comment by TalhaMunir-JD** [comment]
> @TalhaMunir-JD Please explain why these changes are necessary? What value are you adding?

I fixed the typo of 'PostgreSQL' at line 6 and added the references at the end of the file.

**Comment by jrgemignani** [comment]
@TalhaMunir-JD Please add a brief explanation to the extended description of the commit log. Then I will merge your changes.

**Comment by jrgemignani** [comment]
> @TalhaMunir-JD Please add a brief explanation to the extended description of the commit log. Then I will merge your changes.

I'm sorry, I should have been more clear. The title was fine, I was referring to the commit message extended description. The new title is too long and should be put back to what it was.

**Comment by TalhaMunir-JD** [comment]
> 

Commit message updated.

**Pull request closed without merging**
