### PR TITLE
Haversine trigonometric function added

### PR DESCRIPTION
**Pull request by Allison-E**
* Implemented the [`haversin()` Cypher trigonometric function](https://neo4j.com/docs/cypher-manual/current/functions/mathematical-trigonometric/#functions-haversin).
* Wrote regression tests for the `haversin()` function.

More about the Haversine trigonometric function [here](https://en.wikipedia.org/wiki/Haversine_formula).

### CODE REVIEW

**Comment by dehowef** [comment]
Looks good, but can you remove the changes you have made to the .gitignore file? Those are personal config changes we don't want them pushed to the main branch. Thank you @Allison-E

**Comment by Allison-E** [comment]
> Looks good, but can you remove the changes you have made to the .gitignore file? Those are personal config changes we don't want them pushed to the main branch. Thank you @Allison-E

Thank you. I've reverted the changes made.

**Comment by jrgemignani** [comment]
@Allison-E This PR needs to be rebased against the current master due to changes to the age--x.x.x.sql file.

**Comment by jrgemignani** [comment]
> @Allison-E This PR needs to be rebased against the current master due to changes to the age--x.x.x.sql file.

@Allison-E Two points -

1. The age--x.x.x.sql file was split up, your PR includes it again. You need to put your new function into the appropriate sql file for it. See the Makefile to see how age--x.x.x.sql was broken up. You likely need to bring your local repo up-to-date.
2. I don't see the `haversin` function here, I see a date function?

**Review by jrgemignani — CHANGES_REQUESTED** [review]
See comments

**Comment by Allison-E** [comment]
Thanks for pointing that out, @jrgemignani. I've reviewed the changes. I'll work on it and push the correct thing tomorrow.

**Comment by jrgemignani** [comment]
@Allison-E Any update?

**Pull request closed without merging**
