### PR TITLE
Remove check for scalar(vertex,edge or path) agtypes in unwind

### PR DESCRIPTION
**Pull request by MuhammadTahaNaveed**
- Removed check that was disabling unwind to be used on arrays with elements of type vertex,edge or path. 
- Added regression tests for unwind.

### CODE REVIEW

**Comment by MuhammadTahaNaveed** [comment]
Hi @emotionbug,

I did not modify those after seeing this comment. 

What do you think, should it be modified?

**Comment by emotionbug** [comment]
I think that variable is for the constraint you removed.
Since you've already determined that the constraint is unnecessary and removed it, I think the comments and code around it should also be modified.

Because even if you don't, it's already doing nothing with the variable, and it's not what the comment says.

**Comment by MuhammadTahaNaveed** [comment]
> I think that variable is for the constraint you removed.
> Since you've already determined that the constraint is unnecessary and removed it, I think the comments and code around it should also be modified.
> 
> Because even if you don't, it's already doing nothing with the variable, and it's not what the comment says.
> 

Ok thanks. I will update the PR.

**Comment by jrgemignani** [comment]
@MuhammadTahaNaveed I'm not sure why your comments say Co-authored-by you?

**Comment by MuhammadTahaNaveed** [comment]
> @MuhammadTahaNaveed I'm not sure why your **commit description** comments say Co-authored-by you?

@jrgemignani Fixed it.

**Pull request merged**
