### PR TITLE
[PROPOSAL] I'd like to propose an adding a AGE API Server

### PR DESCRIPTION
**Pull request by yjy44**
Hello Everyone. I want to propose adding a AGE API Server Project.

It has the function of requesting a query in Cypher or GraphQL form from an existing RDB such as Oracle or MySQL and receiving the result in the requested form. To store related metadata and configure basic data, AGE and This product utilizes Graphizer. To achieve this, we are setting up the project to be undertaken and devising the architecture. As a result, it is an API to increase the usability of AGE.

It is currently in the planning stage, and you can see the basic concept through the README of the repository. And this PR is a kind of proposal, so I just made this PR as a draft and allowed edits by maintainers.

Currently, we are in the planning stage and have requested PR through Branch. Therefore, it should never be merged into Master Branch.

If you have any question or suggestion, I'd be thankful.

Thank you. And have a nice day.

### CODE REVIEW

**Comment by mingfang** [comment]
I've created a full stack "AGE viewer" that has a frontend sending pure cypher to an API backend.
For example.
This frontend URL
https://age-playground.rebelsoft.com/graph/playground?q=MERGE%20(v1%3AHELLO)-%5Be%3ATO%5D-%3E(v2%3AWORLD)%0ARETURN%20*

makes this API call

https://age-playground.rebelsoft.com/api/graph/playground/cypher?q=MERGE%20(v1%3AHELLO)-%5Be%3ATO%5D-%3E(v2%3AWORLD)%0ARETURN%20*

and the result is in JSON
```json
{
    "sql": "\n            SELECT * FROM cypher('playground', $$\n                MERGE (v1:HELLO)-[e:TO]->(v2:WORLD)\nRETURN *\n            $$) AS (v1 agtype, e agtype, v2 agtype)\n        ",
    "data": [
        {
            "v1": {
                "id": 1407374883553281,
                "label": "HELLO",
                "properties": {}
            },
            "e": {
                "id": 1688849860263937,
                "label": "TO",
                "end_id": 1970324836974593,
                "start_id": 1407374883553281,
                "properties": {}
            },
            "v2": {
                "id": 1970324836974593,
                "label": "WORLD",
                "properties": {}
            }
        }
    ]
}
```

**Comment by jrgemignani** [comment]
@aked21 @dehowef @eyab What are your thoughts on @mingfang ?

**Comment by dehowef** [comment]
@mingfang Wow! I am impressed with it. I think that this has great potential.

**Comment by dehowef** [comment]
Okay your proposal is intetesting but this commit wipes the entire repo @yjy44

**Comment by jrgemignani** [comment]
@yjy44 I'm afraid that the **API_Server** branch was created incorrectly. I will have to close this PR, recreate the branch, and then you can resubmit this PR against that branch. The new branch will be called **PROPOSAL_API_Server**. Additionally, I think you should consider looking into the work @mingfang has done.

**Comment by jrgemignani** [comment]
@yjy44 The branch **PROPOSAL_API_Server** is now available for your PR. You will need to clean out all of the unnecessary files prior to adding anything. Please make sure that is done with a PR specifically stating that before anything else. Then you can use PRs to add in your stuff.

**Pull request closed without merging**
