### PR TITLE
[Age-Viewer-Go-Desktop] Fix Routes and build issues

### PR DESCRIPTION
**Pull request by farakh-shahid**
[Age-Viewer-Go-Desktop]: Restructured routes into a separate folder, removed console.log statements, separated styles into styles.css, and resolved build issues

### CODE REVIEW

**Comment by saadjameel** [comment]
@aked21 Please merge. Reviewed.

**Comment by saadjameel** [comment]
@aked21 Please merge

**Comment by aked21** [comment]
@saadjameel @farakh-shahid please resolve the conflicts in the source

**Comment by farakh-shahid** [comment]
@aked21 conflicts resolved kindly merge.

**Comment by saadjameel** [comment]
@aked21 Please merge conflicts resolved

**Comment by dehowef** [comment]
Outdated

**Pull request closed without merging**
