### PR TITLE
Barbell graph generation

### LINKED ISSUE #275: Barbell Graph
the barbell graph is two complete graphs connected by a bridge path

Syntax:
```
ag_catalog.age_create_tadpole_graph(graph_name Name,
                                    m int,
                                    n int, 
                                    vertex_label_name Name DEFAULT = NULL,
                                    vertex_properties agtype DEFAULT = NULL,
                                    edge_label_name Name DEAULT = NULL,
                                    edge_properties agtype DEFAULT = NULL,
                                    bidirectional bool DEFAULT = true)

```

Input:

- graph_name - Name of the graph to be created
- m - number of vertices in both complete graphs
- n - number of vertices in the bridge path.
- vertex_label_name - Name of the label to assign each vertex to.
- vertex_properties - Property values to assign each vertex. Default is NULL
- edge_label_name - Name of the label to assign each edge to.
- edge_properties - Property values to assign each edge. Default is NULL
- bidirectional - Bidirectional True or False. Default True.

https://en.wikipedia.org/wiki/Barbell_graph

### PR DESCRIPTION
**Pull request by markgomer**
On `src/backend/utils/graph_generation.c`:
Added function to create a Barbell Graph  
   
* ~~Modified function create_complete_graph to return the Oid~~
~~of the created graph;~~
* Created auxiliary function to get_next_val_internal;  
* Currently creates a bridge of no vertexes between graphs,  
will be implemented next.

---

On `age--1.2.0.sql`:
Reflect modifications in graph_generation.c  
  
* ~~Changed return type of create_complete_graph;~~
* Added signature to age_create_barbell_graph;

Resolves #275;

### CODE REVIEW

**Comment by jrgemignani** [comment]
@markgomer 

Please try to verify that your PRs successfully build, without errors, before submitting them; this PR failed. If it did successfully build, please check that your build environment is set up correctly. 

Additionally, make sure that you follow our coding standard https://age.apache.org/contribution/guide/#code-style-guilde

**Comment by jrgemignani** [comment]
@markgomer 

> Additionally, make sure that you follow our coding standard https://age.apache.org/contribution/guide/#code-style-guilde

**Comment by jrgemignani** [comment]
@markgomer Please verify that your code follows our coding standards.

**Comment by markgomer** [comment]
@jrgemignani I don't see where the code doesn't match the standards. I've read the documentation through. Could you point me to what I have to fix?

**Comment by jrgemignani** [comment]
> @jrgemignani I don't see where the code doesn't match the standards. I've read the documentation through. Could you point me to what I have to fix?

There are minor indentation issues and a few if/else statements that are missing braces {}. All if/else statements are required to have braces, even if there is only one line. I know that it is a bit confusing as some of the code doesn't follow that standard, but that code predates the adoption of braces for all if/else statements.

**Comment by jrgemignani** [comment]
@markgomer Additionally, PG_FUNCTION_INFO_V1 is incorrectly placed. There are 2, one from this commit, the other not. If you could please fix both, that would be great.

**Comment by markgomer** [comment]
@jrgemignani, thank you for your time. I have fixed what you pointed. Please let me know if there's anything else left for fixing.

**Comment by markgomer** [comment]
I'll investigate the issue with the test. I'm not sure what happened, since I didn't change anything that would break the code since the last test which passed.

**Review by jrgemignani — APPROVED** [review]

**Comment by jrgemignani** [comment]
@markgomer I overlooked that you need to have regression tests created to test this feature and added to the PR. Could you please create a PR for regression tests for this feature.

**Comment by markgomer** [comment]
> @markgomer I overlooked that you need to have regression tests created to test this feature and added to the PR. Could you please create a PR for regression tests for this feature.

Of course @jrgemignani, I'm already working on that.

**Comment by jrgemignani** [comment]
@markgomer Thank you! Next time, though, the regression tests need to be included in the PR with the feature or bug fix.

**Pull request merged**
