### PR TITLE
[Age-viewer-go] Server function to disconnect database add to backend.

### PR DESCRIPTION
**Pull request by KamleshKumar427**

### CODE REVIEW

**Comment by KamleshKumar427** [comment]
API function to disconnect database add to backend and documentation for working of backend added.

**Comment by saadjameel** [comment]
@aked21 please merge I have reviewed

**Comment by aked21** [comment]
@KamleshKumar427 @saadjameel 
Please fix the conflicts to get merged

**Comment by KamleshKumar427** [comment]
@aked21 Conflicts are resolved. now.

**Pull request merged**
