### PR TITLE
[Viewer Desktop Go] Fix .gitignore file.

### PR DESCRIPTION
**Pull request by AhmarZaidi**
Edited the `.gitignore` file with Wails and Golang ignore files and directories following the standard practice.

### CODE REVIEW

**Comment by saadjameel** [comment]
@aked21 Please merge I've reviewed

**Comment by aked21** [comment]
@AhmarZaidi @saadjameel 
Please fix the conflicts

**Comment by saadjameel** [comment]
Let me check

**Comment by AhmarZaidi** [comment]
I've resolved the conflicts.

**Pull request merged**
