### PR TITLE
Cast bool to pg_bigint

### PR DESCRIPTION
**Pull request by Zainab-Saad**
Casting bool to pg_bigint is implemented in this PR

### CODE REVIEW

**Comment by Zainab-Saad** [comment]
This PR is follow up of issue #828

**Comment by jrgemignani** [comment]
@Zainab-Saad You also need to check (add regression tests and possibly code) for casting a Boolean to an integer - not just to pg_bigint, which is going from an agtype to a pg type.

**Comment by jrgemignani** [comment]
@Zainab-Saad 

That is fine to leave out ::pg_float8. 

Yes, I think I conflated the 2 PRs. So ignore that comment.

**Comment by jrgemignani** [comment]
@Zainab-Saad If you could be a bit more descriptive in the commit log extended description - the big box. Otherwise, everything else looks good!

image

**Comment by Zainab-Saad** [comment]
@jrgemignani Done

**Pull request merged**
