### PR TITLE
Added cbrt() function

### PR DESCRIPTION
**Pull request by titoausten**
- Same as PostgreSQL's [cbrt()](https://www.postgresql.org/docs/current/functions-math.html#) mathematical function.
- Added regression tests.

### CODE REVIEW

**Comment by rafsun42** [comment]
@titoausten 

This can be done like this-
```
(pg-15.4) agedev=# SELECT * from cypher('graph', $$
    RETURN (pg_catalog.cbrt(27::pg_float8))           
$$) as (result real);
 result 
--------
      3
(1 row)
```

Do you think we should add a function that PG already provides?

**Comment by titoausten** [comment]
> @titoausten 
> 
> This can be done like this-
> ```
> (pg-15.4) agedev=# SELECT * from cypher('graph', $$
>     RETURN (pg_catalog.cbrt(27::pg_float8))           
> $$) as (result real);
>  result 
> --------
>       3
> (1 row)
> ```
> 
> Do you think we should add a function that PG already provides?

Yes, It makes the query clear and concise.

**Comment by rafsun42** [comment]
@titoausten 

How about we find a way to implicity cast types and qualify the function name (with pg_catalog, for example) so the queries can be written concisely using PG's functions?
```
SELECT * from cypher('graph', $$
    RETURN cbrt(27)           
$$) as (result real);
```

This will allow us to use any PG functions while avoiding unnecessary reimplementations.

**Comment by titoausten** [comment]
> @titoausten 
> 
> How about we find a way to implicity cast types and qualify the function name (with pg_catalog, for example) so the queries can be written concisely using PG's functions?
> ```
> SELECT * from cypher('graph', $$
>     RETURN cbrt(27)           
> $$) as (result real);
> ```
> 
> This will allow us to use any PG functions while avoiding unnecessary reimplementations.

This seems fine.

**Comment by jrgemignani** [comment]
Atm, unnecessary.

**Pull request closed without merging**
