### PR TITLE
Simplified some if statements

### PR DESCRIPTION
**Pull request by MatheusFarias03**
Some if statements were reduced using a ternary operator instead.

### CODE REVIEW

**Comment by dehowef** [comment]
Hi, thank you for these changes, but I am of the opinion that if-else statements are more readable in most of these cases. I have done very limited research into if ternary operators are faster than if-else statements, but from what I have seen on the web, they are almost equivalent in speed when it comes to using C. @jrgemignani @rafsun42 @muhammadshoaib if you'd like to give your input as well, that'd be good

**Comment by jrgemignani** [comment]
@MatheusFarias03 I tend to agree with @dehowef here. Ternary operators are good in some places but tend to make it more difficult to read and debug in others. We do use them in some places and don't ban their usage. But, generally, I find them unnecessary most of the time and I tend to avoid them, unless necessary.

Here is a SO article about them -

[https://stackoverflow.com/questions/160218/to-ternary-or-not-to-ternary](https://stackoverflow.com/questions/160218/to-ternary-or-not-to-ternary)

**Comment by MatheusFarias03** [comment]
Oh ok! I've also created some PRs like this one, should I close them all?

**Comment by jrgemignani** [comment]
@MatheusFarias03 I hate to say yes because I [we] appreciate your work and desire to make AGE better,... but, yeah,... I don't think these add value. That is my opinion, at least. @dehowef ? @rafsun42

**Comment by rafsun42** [comment]
@MatheusFarias03 My opinion- I appreciate your effort, but I would prefer readability if performance is unchanged.

**Comment by MatheusFarias03** [comment]
Okay folks! I'll close them, no problem! :+1:

**Comment by dehowef** [comment]
@jrgemignani @MatheusFarias03 I wrote transform_cypher_union, which largely referenced the transformSetOperationStmt code in Postgres. I followed a lot of their coding style choices. I think that a good point the thread John linked also points out that nested if/else blocks also allow for debuggers to place breakpoints on certain statements, which condensed ternary operators don't allow for. That is another dimension of "readability" that I think is important. Thanks for understanding @MatheusFarias03 , we really do appreciate your enthusiasm and effort.

**Comment by dehowef** [comment]
I think that this preference in code will differ from project to project. Maybe some projects would prefer the condensed statements and reduced number of lines. But, on a project like AGE where we oftentimes are in the debugger looking at code, and oftentimes code someone else wrote, I think it's nice to have somewhat more atomized code blocks to aid with that.

**Pull request closed without merging**
